services:
  # Production service
  foodstuff-calculator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foodstuff-calculator
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost/",
        ]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

  # Development service
  foodstuff-calculator-dev:
    image: node:22.12.0-alpine
    container_name: foodstuff-calculator-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: sh -c "yarn install && yarn dev --host 0.0.0.0"
    stdin_open: true
    tty: true
